FROM maven:latest AS build
WORKDIR /usr/app
COPY . /usr/app/
RUN mvn install

FROM openjdk:11-jdk
WORKDIR /usr/app
COPY --from=build /usr/app/target/spring-petclinic-2.7.0-SNAPSHOT.jar /usr/app
EXPOSE 8080
CMD ["java","-jar","spring-petclinic-2.7.0-SNAPSHOT.jar"]


